clip: add support tmux

diff --git a/bin/clip b/bin/clip
--- a/bin/clip
+++ b/bin/clip
@@ -4,9 +4,16 @@ SIZE_MAX=74994
 OSC=$'\e]'
 BEL=$'\a'
 
-escape_for_tmux() {
-  sed -e 's/^/\x1bPtmux;/' -e 's/\x1b/\x1b\x1b/g' -e 's/$/\x1b\\/'
-}
+if [[ "$TERM" = "tmux" ]] || [[ "${TERM:0:5}" = "tmux-" ]]; then
+  if [[ "$(tmux show-options -v set-clipboard)" = "off" ]]; then
+    echo >&2 'clip: Error: Cannot set clipboard because tmux "set-clipboard" option is "off".'
+    echo >&2 '             Run `tmux set-options -g set-clipboard on` or append next config to .tmux.conf'
+    echo >&2 ''
+    echo >&2 '             set -g set-clipboard on'
+    echo >&2 ''
+    exit 1
+  fi
+fi
 
 data="$(cat "$@")"
 size="${#data}"
@@ -18,10 +25,6 @@ fi
 
 encoded_data="$(echo -n "$data" | base64 | tr -d '\r\n')"
 
-if [ "${TERM:0:4}" = "tmux" ]; then
-  echo -en "${OSC}52;c;${encoded_data}${BEL}" | escape_for_tmux
-else
-  echo -en "${OSC}52;c;${encoded_data}${BEL}"
-fi
+echo -en "${OSC}52;c;${encoded_data}${BEL}"
 
 
